name: Deploy CDK project

on:
  push:

jobs:
  synth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Synthesize CloudFormation Template
        run: |
          npm install -g aws-cdk
          cdk synth
          echo "Synth successful"

      - name: Deploy CDK Stack
        run: |
          cdk deploy --require-approval never
          echo "Deployed successfully"
